version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: brighte-eats-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brighte_eats
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: brighte-eats-backend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/brighte_eats?schema=public'
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start:dev"

volumes:
  pgdata:
