version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brighte_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: production  
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/brighte_db
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes: []  # No volume mounts in production
    command: ["./entrypoint.sh"]

volumes:
  pgdata:
